from wave_pay.exceptions.unexpected_error import UnexpectedError


class ConnectionError(UnexpectedError):
    pass
